### PR TITLE
Added Sumith1896's GSoC 2015 proposal

### PR DESCRIPTION
**Pull request by sumith1896**
ping @saketkc

### CODE REVIEW

**Comment by saketkc** [comment]
Merged. Thanks!

**Comment by sumith1896** [comment]
Thank you!
But why close instead of direct merge?

**Comment by saketkc** [comment]
Cherry picked  as  9f72f26e6b70c1887649e61fe3828e2f45871303. You remain the author. I am a committer. I avoid the Github merge button and merge everything locally.

**Comment by sumith1896** [comment]
Oh! Any advantage of doing that?

**Comment by saketkc** [comment]
Yes, it helps me keep the commit logs clean(Avoids 'Merge ... from ...'). Easy to track down what and who added what.

**Comment by sumith1896** [comment]
Oh yes! That's there. Now I get it.

Awesome work this. Keep this going.

**Pull request closed without merging**
