### PR TITLE
coala: KaranSharma-Extend-Linter-Integration

### PR DESCRIPTION
**Pull request by mr-karan**
MD wasn't being converted properly so I only added the PDF

### CODE REVIEW

**Comment by saketkc** [comment]
Hi @mr-karan, con tgratulations for GSoC! Could you please let me know what issues you are facing doing a markdown conversion?

My policy is to keep markdowns as they are readily indexed, faster etc.

**Comment by mr-karan** [comment]
I have lost my original md file, sadly. Only have the PDF. So I went from PDF to docx to md. pandoc wasn't able to convert the `code` part in the docx. I'll try again though. Can you suggest an alternative ? :)

**Comment by saketkc** [comment]
That's perfectly okay. Let me know if you can have a markdown instead.
I used this:

```
pdftohtml -enc UTF-8 -s -nomerge coala-KaranSharma-Extend-Linter-Integration.pdf                 
pandoc -s -S coala-KaranSharma-Extend-Linter-Integration-html.html -t markdown_github -o coala.md
```

and it looked mostly okay.

**Comment by saketkc** [comment]
@mr-karan Any updates?

**Pull request closed without merging**
